#!/usr/bin/env bash
# this script fixes the container so that Nginx is running as the nginx user
#!/bin/bash
chmod -R 755 /etc/nginx/
pkill -9 apache2
sed -i 's/8080/8081/g' /etc/apache2/ports.conf
service apache2 restart
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
service nginx restart

