#!/usr/bin/env bash
# make it short and sweet, it will also solve the issue of nginx not listening to port 80 as well
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
service nginx restart
service nginx stop
