#!/usr/bin/env bash
# this script will allow us to automate the file transfer to our remote host
# PATH_TO_FILE = "$1", IP = "$2", USERNAME = "$3", PATH_TO_SSH_KEY = "$4"
if [ $# -lt 4 ];
then 
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
fi
