#!/usr/bin/env bash
# this script will allow us to automate the file transfer to our remote host
if [ $# -lt 4 ]; then 
	echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
	exit 1
fi
PATH_TO_FILE = "$1"
IP = "$2"
USERNAME = "$3"
PATH_TO_SSH_KEY = "$4"
scp -o StrictKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP"
exit 0
